### ISSUE TITLE
$my_group->samples() should be more lazy

### ISSUE THREAD

**Issue by istreeter** [EMBL-EBI-GCA/BioSD#3]
The subroutine "samples" in BioSD::Group now does a fetch from the REST server for every sample belonging to the group. This should be changed to return lazy samples that do a fetch from the REST server when needed.

To facilitate this change, the "new" subroutine in BioSD::Group and BioSD::Sample should allow session to be not defined.  If session is not defined then it attaches the default session.  Then it searches the session cache to see if itself already exists in the cache.

**Comment by davidrichardson** [comment]
See pull request #4
